services:
  web:
    build: .
    volumes:
      - ${HOST_UPLOAD_PATH}:/app/uploads
    networks:
      - tunnel
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped

networks:
  tunnel:
    external: true
