services:
  web:
    container_name: personalweb
    build: .
    user: "1000:1000"
    volumes:
      - ${HOST_UPLOAD_PATH}:/app/uploads
    networks:
      - tunnel
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped

networks:
  tunnel:
    external: true
